; Listing generated by Microsoft (R) Optimizing Compiler Version 19.33.31629.0 

	TITLE	C:\Users\practicas\Downloads\spd_p9_tejado_vS2010_alumnos(1)\spd_p9_tejado_vS2010_alumnos\ej3\Debug\querypmrdtsc.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

msvcjmc	SEGMENT
__998F0ADD_concurrencysal@h DB 01H
__B143C5DE_sal@h DB 01H
__ABD98F87_vadefs@h DB 01H
__F56FDA8E_vcruntime@h DB 01H
__6569C2CA_corecrt@h DB 01H
__A2143F22_corecrt_stdio_config@h DB 01H
__829E1958_corecrt_wstdio@h DB 01H
__6DFAE8B8_stdio@h DB 01H
__11B29F93_xkeycheck@h DB 01H
__CE2ECDB0_yvals_core@h DB 01H
__6DA2CFDE_limits@h DB 01H
__ED296E1D_climits DB 01H
__F83CB273_vcruntime_new@h DB 01H
__A31D6D99_vcruntime_new_debug@h DB 01H
__49916C16_crtdbg@h DB 01H
__6ADFD0E6_crtdefs@h DB 01H
__55C32E17_use_ansi@h DB 01H
__DF86FA50_yvals@h DB 01H
__741AE07E_corecrt_math@h DB 01H
__91D68F2D_math@h DB 01H
__6C20D4D3_corecrt_malloc@h DB 01H
__C9393812_stddef@h DB 01H
__D493B9BD_corecrt_search@h DB 01H
__1473E23E_corecrt_wstdlib@h DB 01H
__B49664B7_stdlib@h DB 01H
__69C64CEF_cstdlib DB 01H
__AECD1C5E_xtr1common DB 01H
__63AFB171_intrin0@inl@h DB 01H
__73F269ED_intrin0@h DB 01H
__D3F9CB69_cmath DB 01H
__549A4081_cstdio DB 01H
__CDDAF8CA_errno@h DB 01H
__13BFA219_vcruntime_string@h DB 01H
__1FEB9909_corecrt_memcpy_s@h DB 01H
__A751F051_corecrt_memory@h DB 01H
__9200769A_corecrt_wstring@h DB 01H
__32E5F013_string@h DB 01H
__2554E40F_cstring DB 01H
__C6E16F6F_corecrt_wconio@h DB 01H
__5DB64B66_corecrt_wctype@h DB 01H
__CB8D9B53_corecrt_wdirect@h DB 01H
__A9063C41_corecrt_share@h DB 01H
__6D390390_corecrt_wio@h DB 01H
__61BDDCD5_corecrt_wprocess@h DB 01H
__1157D6BA_corecrt_wtime@h DB 01H
__64F617E8_types@h DB 01H
__1DC1E279_stat@h DB 01H
__93DC0B45_wchar@h DB 01H
__CE1196D2_cwchar DB 01H
__CC0D9642_cstddef DB 01H
__83497CEE_initializer_list DB 01H
__A9D45E76_xstddef DB 01H
__8DD113E4_iosfwd DB 01H
__D3D4E1E1_stdint@h DB 01H
__D498AD92_cstdint DB 01H
__5F1B5958_type_traits DB 01H
__5ECBC964_utility DB 01H
__BF0C991C_xutility DB 01H
__AEA02E5C_iterator DB 01H
__5B81F060_share@h DB 01H
__48904EDB___msvc_system_error_abi@hpp DB 01H
__C9BB347A_cerrno DB 01H
__20BB4341_malloc@h DB 01H
__3C5D8049_corecrt_terminate@h DB 01H
__6F7F00BD_eh@h DB 01H
__ABF368CB_vcruntime_exception@h DB 01H
__A280BE70_exception DB 01H
__158E8E48_float@h DB 01H
__27DE8B06_cfloat DB 01H
__C034A86A_isa_availability@h DB 01H
__4138C662_limits DB 01H
__643B2442_new DB 01H
__A88C32A6_xatomic@h DB 01H
__345EAAA7_xmemory DB 01H
__408D2C3B_xstring DB 01H
__2BCE842D_stdexcept DB 01H
__8DB613E0_xcall_once@h DB 01H
__7713EF5F_xerrc@h DB 01H
__A0B61CF9_time@h DB 01H
__154A5761_ctime DB 01H
__09C87A5D_xtimec@h DB 01H
__348D19A4_xthreads@h DB 01H
__2A0D9AA0_atomic DB 01H
__32EB01C0_system_error DB 01H
__365A3D9C_vcruntime_typeinfo@h DB 01H
__CFD36A05_typeinfo DB 01H
__FD96CAEC_memory DB 01H
__D1D39DE3_xfacet DB 01H
__BABFE1D0___msvc_xlocinfo_types@hpp DB 01H
__B2D2BA86_ctype@h DB 01H
__5B51A726_cctype DB 01H
__A3D09DBA_locale@h DB 01H
__FA6A903E_clocale DB 01H
__D05A89CD_xlocinfo DB 01H
__9FB3580A_xlocale DB 01H
__E9BFFEDE_xiosbase DB 01H
__296E3C91_streambuf DB 01H
__01343E1D_xlocnum DB 01H
__9CF61E54_ios DB 01H
__8CA382CE_ostream DB 01H
__EF73B7F4_istream DB 01H
__DD75E303_iostream DB 01H
__43B709E2_setjmp@h DB 01H
__90E38594_mmintrin@h DB 01H
__75BAB6DA_xmmintrin@h DB 01H
__10D83F16_emmintrin@h DB 01H
__CF79579F_pmmintrin@h DB 01H
__7FA0241D_tmmintrin@h DB 01H
__569B319E_smmintrin@h DB 01H
__33F9B852_nmmintrin@h DB 01H
__E642421C_wmmintrin@h DB 01H
__2DD60F1B_zmmintrin@h DB 01H
__1AC2ADD1_immintrin@h DB 01H
__A0014C94_ammintrin@h DB 01H
__8BFBB543_mm3dnow@h DB 01H
__6581B595_intrin@h DB 01H
__FA81DC18_querypmrdtsc@h DB 01H
__7E111B0C_querypmrdtsc@cpp DB 01H
msvcjmc	ENDS
CONST	SEGMENT
$SG71204 DB	'C:\Program Files\Microsoft Visual Studio\2022\Profession'
	DB	'al\VC\Tools\MSVC\14.33.31629\include\xlocale', 00H
	ORG $+3
$SG71350 DB	'invalid argument', 00H
	ORG $+3
$SG71351 DB	'%s', 00H
	ORG $+1
$SG71352 DB	'C:\Program Files\Microsoft Visual Studio\2022\Profession'
	DB	'al\VC\Tools\MSVC\14.33.31629\include\xmemory', 00H
	ORG $+3
$SG71353 DB	'C', 00H, ':', 00H, '\', 00H, 'P', 00H, 'r', 00H, 'o', 00H
	DB	'g', 00H, 'r', 00H, 'a', 00H, 'm', 00H, ' ', 00H, 'F', 00H, 'i'
	DB	00H, 'l', 00H, 'e', 00H, 's', 00H, '\', 00H, 'M', 00H, 'i', 00H
	DB	'c', 00H, 'r', 00H, 'o', 00H, 's', 00H, 'o', 00H, 'f', 00H, 't'
	DB	00H, ' ', 00H, 'V', 00H, 'i', 00H, 's', 00H, 'u', 00H, 'a', 00H
	DB	'l', 00H, ' ', 00H, 'S', 00H, 't', 00H, 'u', 00H, 'd', 00H, 'i'
	DB	00H, 'o', 00H, '\', 00H, '2', 00H, '0', 00H, '2', 00H, '2', 00H
	DB	'\', 00H, 'P', 00H, 'r', 00H, 'o', 00H, 'f', 00H, 'e', 00H, 's'
	DB	00H, 's', 00H, 'i', 00H, 'o', 00H, 'n', 00H, 'a', 00H, 'l', 00H
	DB	'\', 00H, 'V', 00H, 'C', 00H, '\', 00H, 'T', 00H, 'o', 00H, 'o'
	DB	00H, 'l', 00H, 's', 00H, '\', 00H, 'M', 00H, 'S', 00H, 'V', 00H
	DB	'C', 00H, '\', 00H, '1', 00H, '4', 00H, '.', 00H, '3', 00H, '3'
	DB	00H, '.', 00H, '3', 00H, '1', 00H, '6', 00H, '2', 00H, '9', 00H
	DB	'\', 00H, 'i', 00H, 'n', 00H, 'c', 00H, 'l', 00H, 'u', 00H, 'd'
	DB	00H, 'e', 00H, '\', 00H, 'x', 00H, 'm', 00H, 'e', 00H, 'm', 00H
	DB	'o', 00H, 'r', 00H, 'y', 00H, 00H, 00H
	ORG $+2
$SG71354 DB	00H, 00H
	ORG $+2
$SG71355 DB	'"', 00H, 'i', 00H, 'n', 00H, 'v', 00H, 'a', 00H, 'l', 00H
	DB	'i', 00H, 'd', 00H, ' ', 00H, 'a', 00H, 'r', 00H, 'g', 00H, 'u'
	DB	00H, 'm', 00H, 'e', 00H, 'n', 00H, 't', 00H, '"', 00H, 00H, 00H
	ORG $+2
$SG64210 DB	' measures)', 00H
	ORG $+1
$SG64211 DB	'   (in ', 00H
$SG64224 DB	' measures)', 00H
	ORG $+1
$SG64225 DB	'(in ', 00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPAXI@Z		; __empty_global_delete
PUBLIC	?ReadCycles@QPTimer@@AAEXPA_K@Z			; QPTimer::ReadCycles
PUBLIC	?PrintCycles@QPTimer@@AAEXPBDPA_K@Z		; QPTimer::PrintCycles
PUBLIC	?PrintCyclesByIteration@QPTimer@@AAEXPBDPA_KH@Z	; QPTimer::PrintCyclesByIteration
PUBLIC	?GetCyclesByIteration@QPTimer@@AAENPA_KH@Z	; QPTimer::GetCyclesByIteration
PUBLIC	?PrintTimeSeconds@QPTimer@@AAEXPBDPA_K@Z	; QPTimer::PrintTimeSeconds
PUBLIC	?RestCycles@QPTimer@@AAEXPA_K00@Z		; QPTimer::RestCycles
PUBLIC	?AddCycles@QPTimer@@AAEXPA_K00@Z		; QPTimer::AddCycles
PUBLIC	??0QPTimer@@QAE@XZ				; QPTimer::QPTimer
PUBLIC	?NumberOfMeasures@QPTimer@@QAEHXZ		; QPTimer::NumberOfMeasures
PUBLIC	?Start@QPTimer@@QAEXXZ				; QPTimer::Start
PUBLIC	?Stop@QPTimer@@QAEXXZ				; QPTimer::Stop
PUBLIC	?Calibrate@QPTimer@@QAEXXZ			; QPTimer::Calibrate
PUBLIC	?Reset@QPTimer@@QAEXXZ				; QPTimer::Reset
PUBLIC	?ResetAll@QPTimer@@QAEXXZ			; QPTimer::ResetAll
PUBLIC	?PrintTime@QPTimer@@QAEXPBD@Z			; QPTimer::PrintTime
PUBLIC	?PrintCycles@QPTimer@@QAEXPBD@Z			; QPTimer::PrintCycles
PUBLIC	?PrintMeanTime@QPTimer@@QAEXPBD@Z		; QPTimer::PrintMeanTime
PUBLIC	?PrintMeanCycles@QPTimer@@QAEXPBD@Z		; QPTimer::PrintMeanCycles
PUBLIC	?PrintMinimumTime@QPTimer@@QAEXPBD@Z		; QPTimer::PrintMinimumTime
PUBLIC	?PrintMinimumCycles@QPTimer@@QAEXPBD@Z		; QPTimer::PrintMinimumCycles
PUBLIC	?PrintMinimumCyclesByIteration@QPTimer@@QAEXPBDH@Z ; QPTimer::PrintMinimumCyclesByIteration
PUBLIC	?GetMinimumCyclesByIteration@QPTimer@@QAENH@Z	; QPTimer::GetMinimumCyclesByIteration
PUBLIC	??$?6U?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@PBD@Z ; std::operator<<<std::char_traits<char> >
PUBLIC	??$endl@DU?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@@Z ; std::endl<char,std::char_traits<char> >
PUBLIC	??1_Sentry_base@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAE@XZ ; std::basic_ostream<char,std::char_traits<char> >::_Sentry_base::~_Sentry_base
PUBLIC	??0sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAE@AAV12@@Z ; std::basic_ostream<char,std::char_traits<char> >::sentry::sentry
PUBLIC	??1sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAE@XZ ; std::basic_ostream<char,std::char_traits<char> >::sentry::~sentry
PUBLIC	__JustMyCode_Default
EXTRN	___std_terminate:PROC
EXTRN	?uncaught_exception@std@@YA_NXZ:PROC		; std::uncaught_exception
EXTRN	__imp_?sputc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QAEHD@Z:PROC
EXTRN	__imp_?sputn@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QAE_JPBD_J@Z:PROC
EXTRN	__imp_?setstate@?$basic_ios@DU?$char_traits@D@std@@@std@@QAEXH_N@Z:PROC
EXTRN	__imp_?widen@?$basic_ios@DU?$char_traits@D@std@@@std@@QBEDD@Z:PROC
EXTRN	__imp_?_Osfx@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEXXZ:PROC
EXTRN	__imp_??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@P6AAAV01@AAV01@@Z@Z:PROC
EXTRN	__imp_??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@H@Z:PROC
EXTRN	__imp_??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@_K@Z:PROC
EXTRN	__imp_??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@N@Z:PROC
EXTRN	__imp_?put@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV12@D@Z:PROC
EXTRN	__imp_?flush@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV12@XZ:PROC
EXTRN	@__CheckForDebuggerJustMyCode@4:PROC
EXTRN	___CxxFrameHandler3:PROC
EXTRN	__aulldiv:PROC
EXTRN	__ultod3:PROC
EXTRN	__imp_?cout@std@@3V?$basic_ostream@DU?$char_traits@D@std@@@1@A:BYTE
EXTRN	__fltused:DWORD
;	COMDAT xdata$x
xdata$x	SEGMENT
__unwindtable$??1sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAE@XZ DD 0ffffffffH
	DD	FLAT:___std_terminate
__ehfuncinfo$??1sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAE@XZ DD 019930522H
	DD	01H
	DD	FLAT:__unwindtable$??1sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAE@XZ
	DD	2 DUP(00H)
	DD	2 DUP(00H)
	DD	00H
	DD	05H
xdata$x	ENDS
;	COMDAT xdata$x
xdata$x	SEGMENT
__unwindtable$??0sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAE@AAV12@@Z DD 0ffffffffH
	DD	FLAT:__unwindfunclet$??0sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAE@AAV12@@Z$0
__ehfuncinfo$??0sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAE@AAV12@@Z DD 019930522H
	DD	01H
	DD	FLAT:__unwindtable$??0sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAE@AAV12@@Z
	DD	2 DUP(00H)
	DD	2 DUP(00H)
	DD	00H
	DD	01H
xdata$x	ENDS
;	COMDAT xdata$x
xdata$x	SEGMENT
__ehfuncinfo$??1_Sentry_base@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAE@XZ DD 019930522H
	DD	00H
	DD	00H
	DD	2 DUP(00H)
	DD	2 DUP(00H)
	DD	00H
	DD	05H
xdata$x	ENDS
;	COMDAT xdata$x
xdata$x	SEGMENT
__catchsym$??$?6U?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@PBD@Z$5 DD 040H
	DD	00H
	DD	00H
	DD	FLAT:__catch$??$?6U?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@PBD@Z$0
__tryblocktable$??$?6U?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@PBD@Z DD 01H
	DD	01H
	DD	02H
	DD	01H
	DD	FLAT:__catchsym$??$?6U?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@PBD@Z$5
__ehfuncinfo$??$?6U?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@PBD@Z DD 019930522H
	DD	05H
	DD	FLAT:__unwindtable$??$?6U?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@PBD@Z
	DD	01H
	DD	FLAT:__tryblocktable$??$?6U?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@PBD@Z
	DD	2 DUP(00H)
	DD	00H
	DD	01H
__unwindtable$??$?6U?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@PBD@Z DD 0ffffffffH
	DD	FLAT:__unwindfunclet$??$?6U?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@PBD@Z$2
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	0ffffffffH
	DD	FLAT:___std_terminate
	DD	03H
	DD	FLAT:___std_terminate
xdata$x	ENDS
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
_TEXT	SEGMENT
__JustMyCode_Default PROC				; COMDAT
	push	ebp
	mov	ebp, esp
	pop	ebp
	ret	0
__JustMyCode_Default ENDP
_TEXT	ENDS
; Function compile flags: /Ogtp
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ostream
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ios
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ostream
;	COMDAT ??1sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAE@XZ
_TEXT	SEGMENT
__$EHRec$ = -12						; size = 12
??1sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAE@XZ PROC ; std::basic_ostream<char,std::char_traits<char> >::sentry::~sentry, COMDAT
; _this$ = ecx

; 108  :         __CLR_OR_THIS_CALL ~sentry() noexcept {

	push	ebp
	mov	ebp, esp
	mov	eax, DWORD PTR fs:0
	push	-1
	push	__ehhandler$??1sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAE@XZ
	push	eax
	mov	DWORD PTR fs:0, esp
	push	esi
	mov	esi, ecx
	mov	ecx, OFFSET __8CA382CE_ostream
	call	@__CheckForDebuggerJustMyCode@4
	call	?uncaught_exception@std@@YA_NXZ		; std::uncaught_exception
	test	al, al
	jne	SHORT $LN2@sentry

; 109  : #if !_HAS_EXCEPTIONS
; 110  :             const bool _Zero_uncaught_exceptions = true;
; 111  : #elif _HAS_DEPRECATED_UNCAUGHT_EXCEPTION
; 112  :             const bool _Zero_uncaught_exceptions = !_STD uncaught_exception(); // TRANSITION, ArchivedOS-12000909
; 113  : #else // ^^^ _HAS_DEPRECATED_UNCAUGHT_EXCEPTION / !_HAS_DEPRECATED_UNCAUGHT_EXCEPTION vvv
; 114  :             const bool _Zero_uncaught_exceptions = _STD uncaught_exceptions() == 0;
; 115  : #endif // !_HAS_DEPRECATED_UNCAUGHT_EXCEPTION
; 116  : 
; 117  :             if (_Zero_uncaught_exceptions) {
; 118  :                 this->_Myostr._Osfx();

	mov	ecx, DWORD PTR [esi]
	call	DWORD PTR __imp_?_Osfx@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEXXZ
$LN2@sentry:

; 78   :             const auto _Rdbuf = _Myostr.rdbuf();

	mov	ecx, DWORD PTR [esi]
	mov	DWORD PTR __$EHRec$[ebp+8], 0
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ios

; 79   :         return _Mystrbuf;

	mov	eax, DWORD PTR [ecx]
	mov	eax, DWORD PTR [eax+4]
	mov	ecx, DWORD PTR [eax+ecx+56]
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ostream

; 79   :             if (_Rdbuf) {

	test	ecx, ecx
	je	SHORT $LN5@sentry

; 80   :                 _Rdbuf->_Unlock();

	mov	eax, DWORD PTR [ecx]
	call	DWORD PTR [eax+8]
$LN5@sentry:

; 119  :             }
; 120  :         }

	mov	ecx, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, ecx
	pop	esi
	mov	esp, ebp
	pop	ebp
	ret	0
	int	3
	int	3
	int	3
	int	3
	int	3
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
__ehhandler$??1sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAE@XZ:
	npad	1
	npad	1
	mov	eax, OFFSET __ehfuncinfo$??1sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAE@XZ
	jmp	___CxxFrameHandler3
text$x	ENDS
??1sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAE@XZ ENDP ; std::basic_ostream<char,std::char_traits<char> >::sentry::~sentry
; Function compile flags: /Ogtp
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ostream
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ios
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ostream
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\xiosbase
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ostream
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\xiosbase
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ostream
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ios
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ostream
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\xiosbase
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ostream
;	COMDAT ??0sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAE@AAV12@@Z
_TEXT	SEGMENT
_this$ = -16						; size = 4
__$EHRec$ = -12						; size = 12
__Ostr$ = 8						; size = 4
??0sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAE@AAV12@@Z PROC ; std::basic_ostream<char,std::char_traits<char> >::sentry::sentry, COMDAT
; _this$ = ecx

; 91   :         explicit __CLR_OR_THIS_CALL sentry(basic_ostream& _Ostr) : _Sentry_base(_Ostr) {

	push	ebp
	mov	ebp, esp
	push	-1
	push	__ehhandler$??0sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAE@AAV12@@Z
	mov	eax, DWORD PTR fs:0
	push	eax
	mov	DWORD PTR fs:0, esp
	push	ecx
	push	esi
	mov	esi, ecx
	mov	ecx, OFFSET __8CA382CE_ostream
	push	edi
	mov	DWORD PTR _this$[ebp], esi
	call	@__CheckForDebuggerJustMyCode@4

; 70   :         __CLR_OR_THIS_CALL _Sentry_base(basic_ostream& _Ostr) : _Myostr(_Ostr) { // lock the stream buffer, if there

	mov	edi, DWORD PTR __Ostr$[ebp]
	mov	DWORD PTR [esi], edi
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ios

; 79   :         return _Mystrbuf;

	mov	eax, DWORD PTR [edi]
	mov	eax, DWORD PTR [eax+4]
	mov	ecx, DWORD PTR [eax+edi+56]
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ostream

; 72   :             if (_Rdbuf) {

	test	ecx, ecx
	je	SHORT $LN8@sentry

; 73   :                 _Rdbuf->_Lock();

	mov	eax, DWORD PTR [ecx]
	call	DWORD PTR [eax+4]
$LN8@sentry:
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\xiosbase

; 272  :         return _Mystate;

	mov	eax, DWORD PTR [edi]
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ostream

; 91   :         explicit __CLR_OR_THIS_CALL sentry(basic_ostream& _Ostr) : _Sentry_base(_Ostr) {

	mov	DWORD PTR __$EHRec$[ebp+8], 0
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\xiosbase

; 272  :         return _Mystate;

	mov	eax, DWORD PTR [eax+4]

; 291  :         return rdstate() == ios_base::goodbit;

	cmp	DWORD PTR [eax+edi+12], 0

; 272  :         return _Mystate;

	lea	ecx, DWORD PTR [eax+edi]
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ostream

; 92   :             if (!_Ostr.good()) {

	je	SHORT $LN2@sentry

; 93   :                 _Ok = false;

	xor	al, al

; 94   :                 return;

	jmp	SHORT $LN23@sentry
$LN2@sentry:
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ios

; 69   :         return _Tiestr;

	mov	ecx, DWORD PTR [ecx+60]
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ostream

; 98   :             if (!_Tied || _Tied == &_Ostr) {

	test	ecx, ecx
	je	SHORT $LN4@sentry
	cmp	ecx, edi
	je	SHORT $LN4@sentry

; 100  :                 return;
; 101  :             }
; 102  : 
; 103  :             _Tied->flush();

	call	DWORD PTR __imp_?flush@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV12@XZ
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\xiosbase

; 291  :         return rdstate() == ios_base::goodbit;

	mov	eax, DWORD PTR [edi]
	mov	eax, DWORD PTR [eax+4]
	cmp	DWORD PTR [eax+edi+12], 0
	sete	al
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ostream

; 104  :             _Ok = _Ostr.good(); // store test only after flushing tie

	jmp	SHORT $LN23@sentry
$LN4@sentry:

; 99   :                 _Ok = true;

	mov	al, 1
$LN23@sentry:

; 105  :         }

	mov	BYTE PTR [esi+4], al
	mov	eax, esi
	mov	ecx, DWORD PTR __$EHRec$[ebp]
	pop	edi
	pop	esi
	mov	DWORD PTR fs:0, ecx
	mov	esp, ebp
	pop	ebp
	ret	4
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
__unwindfunclet$??0sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAE@AAV12@@Z$0:
	mov	ecx, DWORD PTR _this$[ebp]
	jmp	??1_Sentry_base@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAE@XZ ; std::basic_ostream<char,std::char_traits<char> >::_Sentry_base::~_Sentry_base
	int	3
	int	3
	int	3
	int	3
	int	3
__ehhandler$??0sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAE@AAV12@@Z:
	npad	1
	npad	1
	mov	eax, OFFSET __ehfuncinfo$??0sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAE@AAV12@@Z
	jmp	___CxxFrameHandler3
text$x	ENDS
??0sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAE@AAV12@@Z ENDP ; std::basic_ostream<char,std::char_traits<char> >::sentry::sentry
; Function compile flags: /Ogtp
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ostream
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ios
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ostream
;	COMDAT ??1_Sentry_base@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAE@XZ
_TEXT	SEGMENT
__$EHRec$ = -12						; size = 12
??1_Sentry_base@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAE@XZ PROC ; std::basic_ostream<char,std::char_traits<char> >::_Sentry_base::~_Sentry_base, COMDAT
; _this$ = ecx

; 77   :         __CLR_OR_THIS_CALL ~_Sentry_base() noexcept { // destroy after unlocking

	push	ebp
	mov	ebp, esp
	mov	eax, DWORD PTR fs:0
	push	-1
	push	__ehhandler$??1_Sentry_base@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAE@XZ
	push	eax
	mov	DWORD PTR fs:0, esp
	push	esi
	mov	esi, ecx
	mov	ecx, OFFSET __8CA382CE_ostream
	call	@__CheckForDebuggerJustMyCode@4
	mov	ecx, DWORD PTR [esi]
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ios

; 79   :         return _Mystrbuf;

	mov	eax, DWORD PTR [ecx]
	mov	eax, DWORD PTR [eax+4]
	mov	ecx, DWORD PTR [eax+ecx+56]
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ostream

; 79   :             if (_Rdbuf) {

	test	ecx, ecx
	je	SHORT $LN2@Sentry_bas

; 80   :                 _Rdbuf->_Unlock();

	mov	eax, DWORD PTR [ecx]
	call	DWORD PTR [eax+8]
$LN2@Sentry_bas:

; 81   :             }
; 82   :         }

	mov	ecx, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, ecx
	pop	esi
	mov	esp, ebp
	pop	ebp
	ret	0
	int	3
	int	3
	int	3
	int	3
	int	3
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
__ehhandler$??1_Sentry_base@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAE@XZ:
	npad	1
	npad	1
	mov	eax, OFFSET __ehfuncinfo$??1_Sentry_base@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAE@XZ
	jmp	___CxxFrameHandler3
text$x	ENDS
??1_Sentry_base@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAE@XZ ENDP ; std::basic_ostream<char,std::char_traits<char> >::_Sentry_base::~_Sentry_base
; Function compile flags: /Ogtp
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ostream
;	COMDAT ??$endl@DU?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@@Z
_TEXT	SEGMENT
__Ostr$ = 8						; size = 4
??$endl@DU?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@@Z PROC ; std::endl<char,std::char_traits<char> >, COMDAT

; 1005 :     basic_ostream<_Elem, _Traits>& _Ostr) { // insert newline and flush stream

	push	ebp
	mov	ebp, esp
	push	esi
	mov	ecx, OFFSET __8CA382CE_ostream
	call	@__CheckForDebuggerJustMyCode@4
	mov	esi, DWORD PTR __Ostr$[ebp]
	push	10					; 0000000aH
	mov	eax, DWORD PTR [esi]
	mov	ecx, DWORD PTR [eax+4]
	add	ecx, esi
	call	DWORD PTR __imp_?widen@?$basic_ios@DU?$char_traits@D@std@@@std@@QBEDD@Z
	movzx	ecx, al
	push	ecx
	mov	ecx, esi
	call	DWORD PTR __imp_?put@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV12@D@Z
	mov	ecx, esi
	call	DWORD PTR __imp_?flush@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV12@XZ
	mov	eax, esi
	pop	esi

; 1006 :     _Ostr.put(_Ostr.widen('\n'));
; 1007 :     _Ostr.flush();
; 1008 :     return _Ostr;
; 1009 : }

	pop	ebp
	ret	0
??$endl@DU?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@@Z ENDP ; std::endl<char,std::char_traits<char> >
_TEXT	ENDS
; Function compile flags: /Ogtp
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ostream
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\xstring
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ostream
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\xstring
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\xiosbase
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\xstring
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\xiosbase
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ostream
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\xiosbase
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ostream
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\xiosbase
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ostream
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ios
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ostream
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ios
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ostream
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ios
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ostream
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ios
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ostream
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ios
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ostream
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ios
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ostream
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\xiosbase
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ostream
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ios
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ostream
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ios
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ostream
;	COMDAT ??$?6U?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@PBD@Z
_TEXT	SEGMENT
__Ok$ = -40						; size = 8
__Pad$ = -32						; size = 8
$T2 = -28						; size = 1
$T3 = -28						; size = 1
__Count$2$ = -24					; size = 4
__State$ = -20						; size = 4
__$EHRec$ = -16						; size = 16
__Ostr$ = 8						; size = 4
__Val$ = 12						; size = 4
??$?6U?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@PBD@Z PROC ; std::operator<<<std::char_traits<char> >, COMDAT

; 761  : basic_ostream<char, _Traits>& operator<<(basic_ostream<char, _Traits>& _Ostr, const char* _Val) {

	push	ebp
	mov	ebp, esp
	push	-1
	push	__ehhandler$??$?6U?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@PBD@Z
	mov	eax, DWORD PTR fs:0
	push	eax
	mov	DWORD PTR fs:0, esp
	sub	esp, 28					; 0000001cH
	push	ebx
	push	esi
	push	edi
	mov	ecx, OFFSET __8CA382CE_ostream
	mov	DWORD PTR __$EHRec$[ebp], esp
	call	@__CheckForDebuggerJustMyCode@4
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\xstring

; 401  :         return _CSTD strlen(reinterpret_cast<const char*>(_First));

	mov	edx, DWORD PTR __Val$[ebp]
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ostream

; 766  :     ios_base::iostate _State = ios_base::goodbit;

	xor	ebx, ebx
	mov	DWORD PTR __State$[ebp], ebx
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\xstring

; 401  :         return _CSTD strlen(reinterpret_cast<const char*>(_First));

	lea	ecx, DWORD PTR [edx+1]
$LL76@operator:
	mov	al, BYTE PTR [edx]
	inc	edx
	test	al, al
	jne	SHORT $LL76@operator
	sub	edx, ecx
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\xiosbase

; 359  :         return _Wide;

	mov	ecx, DWORD PTR __Ostr$[ebp]
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\xstring

; 401  :         return _CSTD strlen(reinterpret_cast<const char*>(_First));

	mov	DWORD PTR __Count$2$[ebp], edx
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\xiosbase

; 359  :         return _Wide;

	mov	eax, DWORD PTR [ecx]
	mov	eax, DWORD PTR [eax+4]
	mov	edi, DWORD PTR [eax+ecx+36]
	mov	esi, DWORD PTR [eax+ecx+32]
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ostream

; 768  :     streamsize _Pad          = _Ostr.width() <= 0 || _Ostr.width() <= _Count ? 0 : _Ostr.width() - _Count;

	test	edi, edi
	jl	SHORT $LN17@operator
	jg	SHORT $LN78@operator
	test	esi, esi
	je	SHORT $LN17@operator
	test	edi, edi
	jl	SHORT $LN17@operator
	jg	SHORT $LN78@operator
	cmp	esi, edx
	jbe	SHORT $LN17@operator
$LN78@operator:
	sub	esi, edx
	sbb	edi, ebx
	jmp	SHORT $LN18@operator
$LN17@operator:
	xorps	xmm0, xmm0
	movlpd	QWORD PTR __Pad$[ebp], xmm0
	mov	edi, DWORD PTR __Pad$[ebp+4]
	mov	esi, DWORD PTR __Pad$[ebp]
$LN18@operator:

; 769  :     const typename _Myos::sentry _Ok(_Ostr);

	push	ecx
	lea	ecx, DWORD PTR __Ok$[ebp]
	call	??0sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAE@AAV12@@Z ; std::basic_ostream<char,std::char_traits<char> >::sentry::sentry

; 770  : 
; 771  :     if (!_Ok) {

	cmp	BYTE PTR __Ok$[ebp+4], 0
	mov	DWORD PTR __$EHRec$[ebp+12], 0
	jne	SHORT $LN8@operator

; 772  :         _State |= ios_base::badbit;

	mov	ebx, 4

; 773  :     } else { // state okay, insert

	jmp	$LN88@operator
$LN8@operator:
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\xiosbase

; 322  :         return _Fmtfl;

	mov	ecx, DWORD PTR __Ostr$[ebp]
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ostream

; 774  :         _TRY_IO_BEGIN

	mov	BYTE PTR __$EHRec$[ebp+12], 1
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\xiosbase

; 322  :         return _Fmtfl;

	mov	eax, DWORD PTR [ecx]
	mov	eax, DWORD PTR [eax+4]
	mov	eax, DWORD PTR [eax+ecx+20]
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ostream

; 775  :         if ((_Ostr.flags() & ios_base::adjustfield) != ios_base::left) {

	and	eax, 448				; 000001c0H
	cmp	eax, 64					; 00000040H
	je	SHORT $LN73@operator
$LL4@operator:

; 776  :             for (; 0 < _Pad; --_Pad) { // pad on left

	test	edi, edi
	jl	SHORT $LN73@operator
	jg	SHORT $LN79@operator
	test	esi, esi
	je	SHORT $LN73@operator
$LN79@operator:
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ios

; 100  :         return _Fillch;

	mov	eax, DWORD PTR [ecx]
	add	ecx, DWORD PTR [eax+4]
	mov	al, BYTE PTR [ecx+64]
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ostream

; 777  :                 if (_Traits::eq_int_type(_Traits::eof(), _Ostr.rdbuf()->sputc(_Ostr.fill()))) {

	mov	ecx, DWORD PTR [ecx+56]
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ios

; 100  :         return _Fillch;

	mov	BYTE PTR $T3[ebp], al
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ostream

; 777  :                 if (_Traits::eq_int_type(_Traits::eof(), _Ostr.rdbuf()->sputc(_Ostr.fill()))) {

	push	DWORD PTR $T3[ebp]
	call	DWORD PTR __imp_?sputc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QAEHD@Z
	cmp	eax, -1
	jne	SHORT $LN2@operator

; 778  :                     _State |= ios_base::badbit; // insertion failed, quit

	lea	ebx, DWORD PTR [eax+5]

; 779  :                     break;

	jmp	SHORT $LN6@operator
$LN2@operator:

; 776  :             for (; 0 < _Pad; --_Pad) { // pad on left

	mov	ecx, DWORD PTR __Ostr$[ebp]
	add	esi, -1
	adc	edi, -1
	jmp	SHORT $LL4@operator
$LN73@operator:
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ios

; 79   :         return _Mystrbuf;

	mov	eax, DWORD PTR [ecx]
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ostream

; 784  :         if (_State == ios_base::goodbit && _Ostr.rdbuf()->sputn(_Val, _Count) != _Count) {

	push	0
	push	DWORD PTR __Count$2$[ebp]
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ios

; 79   :         return _Mystrbuf;

	mov	eax, DWORD PTR [eax+4]
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ostream

; 784  :         if (_State == ios_base::goodbit && _Ostr.rdbuf()->sputn(_Val, _Count) != _Count) {

	push	DWORD PTR __Val$[ebp]
	mov	ecx, DWORD PTR [eax+ecx+56]
	call	DWORD PTR __imp_?sputn@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QAE_JPBD_J@Z
	cmp	eax, DWORD PTR __Count$2$[ebp]
	jne	SHORT $LN80@operator
	test	edx, edx
	jne	SHORT $LN80@operator
	npad	6
$LL82@operator:

; 785  :             _State |= ios_base::badbit;
; 786  :         }
; 787  : 
; 788  :         if (_State == ios_base::goodbit) {
; 789  :             for (; 0 < _Pad; --_Pad) { // pad on right

	test	edi, edi
	jl	SHORT $LN6@operator
	jg	SHORT $LN81@operator
	test	esi, esi
	je	SHORT $LN6@operator
$LN81@operator:
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ios

; 100  :         return _Fillch;

	mov	ecx, DWORD PTR __Ostr$[ebp]
	mov	eax, DWORD PTR [ecx]
	add	ecx, DWORD PTR [eax+4]
	mov	al, BYTE PTR [ecx+64]
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ostream

; 790  :                 if (_Traits::eq_int_type(_Traits::eof(), _Ostr.rdbuf()->sputc(_Ostr.fill()))) {

	mov	ecx, DWORD PTR [ecx+56]
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ios

; 100  :         return _Fillch;

	mov	BYTE PTR $T2[ebp], al
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ostream

; 790  :                 if (_Traits::eq_int_type(_Traits::eof(), _Ostr.rdbuf()->sputc(_Ostr.fill()))) {

	push	DWORD PTR $T2[ebp]
	call	DWORD PTR __imp_?sputc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QAEHD@Z
	cmp	eax, -1
	je	SHORT $LN80@operator

; 785  :             _State |= ios_base::badbit;
; 786  :         }
; 787  : 
; 788  :         if (_State == ios_base::goodbit) {
; 789  :             for (; 0 < _Pad; --_Pad) { // pad on right

	add	esi, -1
	adc	edi, -1
	jmp	SHORT $LL82@operator
$LN80@operator:

; 791  :                     _State |= ios_base::badbit; // insertion failed, quit
; 792  :                     break;
; 793  :                 }
; 794  :             }
; 795  :         }
; 796  : 
; 797  :         _Ostr.width(0);

	or	ebx, 4
$LN6@operator:
	mov	esi, DWORD PTR __Ostr$[ebp]
	mov	DWORD PTR __$EHRec$[ebp+12], 0
	mov	eax, DWORD PTR [esi]
	mov	eax, DWORD PTR [eax+4]
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\xiosbase

; 364  :         _Wide                      = _Newwidth;

	mov	DWORD PTR [eax+esi+32], 0
	mov	DWORD PTR [eax+esi+36], 0
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ostream
	jmp	SHORT $LN22@operator
__catch$??$?6U?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@PBD@Z$0:

; 798  :         _CATCH_IO_(ios_base, _Ostr)

	mov	edx, DWORD PTR __Ostr$[ebp]
	push	1
	push	4
	mov	eax, DWORD PTR [edx]
	mov	ecx, DWORD PTR [eax+4]
	add	ecx, edx
	call	DWORD PTR __imp_?setstate@?$basic_ios@DU?$char_traits@D@std@@@std@@QAEXH_N@Z
	mov	eax, $LN23@operator
	ret	0
$LN23@operator:
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\xiosbase
	mov	ebx, DWORD PTR __State$[ebp]
	mov	DWORD PTR __$EHRec$[ebp+12], 0
$LN88@operator:
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ostream

; 799  :     }
; 800  : 
; 801  :     _Ostr.setstate(_State);

	mov	esi, DWORD PTR __Ostr$[ebp]
$LN22@operator:
	mov	eax, DWORD PTR [esi]
	push	0
	push	ebx
	mov	ecx, DWORD PTR [eax+4]
	add	ecx, esi
	call	DWORD PTR __imp_?setstate@?$basic_ios@DU?$char_traits@D@std@@@std@@QAEXH_N@Z

; 108  :         __CLR_OR_THIS_CALL ~sentry() noexcept {

	mov	DWORD PTR __$EHRec$[ebp+12], 3

; 109  : #if !_HAS_EXCEPTIONS
; 110  :             const bool _Zero_uncaught_exceptions = true;
; 111  : #elif _HAS_DEPRECATED_UNCAUGHT_EXCEPTION
; 112  :             const bool _Zero_uncaught_exceptions = !_STD uncaught_exception(); // TRANSITION, ArchivedOS-12000909

	call	?uncaught_exception@std@@YA_NXZ		; std::uncaught_exception

; 113  : #else // ^^^ _HAS_DEPRECATED_UNCAUGHT_EXCEPTION / !_HAS_DEPRECATED_UNCAUGHT_EXCEPTION vvv
; 114  :             const bool _Zero_uncaught_exceptions = _STD uncaught_exceptions() == 0;
; 115  : #endif // !_HAS_DEPRECATED_UNCAUGHT_EXCEPTION
; 116  : 
; 117  :             if (_Zero_uncaught_exceptions) {

	test	al, al
	jne	SHORT $LN25@operator

; 118  :                 this->_Myostr._Osfx();

	mov	ecx, DWORD PTR __Ok$[ebp]
	call	DWORD PTR __imp_?_Osfx@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEXXZ
$LN25@operator:
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ios

; 79   :         return _Mystrbuf;

	mov	edx, DWORD PTR __Ok$[ebp]
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ostream

; 77   :         __CLR_OR_THIS_CALL ~_Sentry_base() noexcept { // destroy after unlocking

	mov	BYTE PTR __$EHRec$[ebp+12], 4
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ios

; 79   :         return _Mystrbuf;

	mov	ecx, DWORD PTR [edx]
	mov	ecx, DWORD PTR [ecx+4]
	mov	ecx, DWORD PTR [ecx+edx+56]
; File C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\include\ostream

; 79   :             if (_Rdbuf) {

	test	ecx, ecx
	je	SHORT $LN83@operator

; 80   :                 _Rdbuf->_Unlock();

	mov	edx, DWORD PTR [ecx]
	call	DWORD PTR [edx+8]
$LN83@operator:

; 802  :     return _Ostr;
; 803  : }

	mov	ecx, DWORD PTR __$EHRec$[ebp+4]
	mov	eax, esi
	pop	edi
	pop	esi
	mov	DWORD PTR fs:0, ecx
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
__unwindfunclet$??$?6U?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@PBD@Z$2:
	lea	ecx, DWORD PTR __Ok$[ebp]
	jmp	??1sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAE@XZ ; std::basic_ostream<char,std::char_traits<char> >::sentry::~sentry
	int	3
	int	3
	int	3
	int	3
	int	3
__ehhandler$??$?6U?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@PBD@Z:
	npad	1
	npad	1
	mov	eax, OFFSET __ehfuncinfo$??$?6U?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@PBD@Z
	jmp	___CxxFrameHandler3
text$x	ENDS
??$?6U?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@PBD@Z ENDP ; std::operator<<<std::char_traits<char> >
; Function compile flags: /Ogtp
; File C:\Users\practicas\Downloads\spd_p9_tejado_vS2010_alumnos(1)\spd_p9_tejado_vS2010_alumnos\ej3\querypmrdtsc.cpp
_TEXT	SEGMENT
_num$ = 8						; size = 4
?GetMinimumCyclesByIteration@QPTimer@@QAENH@Z PROC	; QPTimer::GetMinimumCyclesByIteration
; _this$ = ecx

; 140  : {

	push	ebp
	mov	ebp, esp
	push	esi
	mov	esi, ecx
	mov	ecx, OFFSET __7E111B0C_querypmrdtsc@cpp
	call	@__CheckForDebuggerJustMyCode@4
	push	DWORD PTR _num$[ebp]
	lea	eax, DWORD PTR [esi+24]
	mov	ecx, esi
	push	eax
	call	?GetCyclesByIteration@QPTimer@@AAENPA_KH@Z ; QPTimer::GetCyclesByIteration
	pop	esi

; 141  : 		return GetCyclesByIteration(&minimumTime,num);
; 142  : }

	pop	ebp
	ret	4
?GetMinimumCyclesByIteration@QPTimer@@QAENH@Z ENDP	; QPTimer::GetMinimumCyclesByIteration
_TEXT	ENDS
; Function compile flags: /Ogtp
; File C:\Users\practicas\Downloads\spd_p9_tejado_vS2010_alumnos(1)\spd_p9_tejado_vS2010_alumnos\ej3\querypmrdtsc.cpp
_TEXT	SEGMENT
_message$ = 8						; size = 4
_num$ = 12						; size = 4
?PrintMinimumCyclesByIteration@QPTimer@@QAEXPBDH@Z PROC	; QPTimer::PrintMinimumCyclesByIteration
; _this$ = ecx

; 134  : {

	push	ebp
	mov	ebp, esp
	push	esi
	mov	esi, ecx
	mov	ecx, OFFSET __7E111B0C_querypmrdtsc@cpp
	call	@__CheckForDebuggerJustMyCode@4
	cmp	BYTE PTR [esi+56], 0
	jne	SHORT $LN2@PrintMinim

; 135  : 	if(!DisableOutput)
; 136  : 		PrintCyclesByIteration(message,&minimumTime,num);

	push	DWORD PTR _num$[ebp]
	lea	eax, DWORD PTR [esi+24]
	mov	ecx, esi
	push	eax
	push	DWORD PTR _message$[ebp]
	call	?PrintCyclesByIteration@QPTimer@@AAEXPBDPA_KH@Z ; QPTimer::PrintCyclesByIteration
$LN2@PrintMinim:
	pop	esi

; 137  : }

	pop	ebp
	ret	8
?PrintMinimumCyclesByIteration@QPTimer@@QAEXPBDH@Z ENDP	; QPTimer::PrintMinimumCyclesByIteration
_TEXT	ENDS
; Function compile flags: /Ogtp
; File C:\Users\practicas\Downloads\spd_p9_tejado_vS2010_alumnos(1)\spd_p9_tejado_vS2010_alumnos\ej3\querypmrdtsc.cpp
_TEXT	SEGMENT
_message$ = 8						; size = 4
?PrintMinimumCycles@QPTimer@@QAEXPBD@Z PROC		; QPTimer::PrintMinimumCycles
; _this$ = ecx

; 128  : {

	push	ebp
	mov	ebp, esp
	push	esi
	mov	esi, ecx
	mov	ecx, OFFSET __7E111B0C_querypmrdtsc@cpp
	call	@__CheckForDebuggerJustMyCode@4
	cmp	BYTE PTR [esi+56], 0
	jne	SHORT $LN2@PrintMinim

; 129  : 	if(!DisableOutput)
; 130  : 		PrintCycles(message,&minimumTime);

	lea	eax, DWORD PTR [esi+24]
	mov	ecx, esi
	push	eax
	push	DWORD PTR _message$[ebp]
	call	?PrintCycles@QPTimer@@AAEXPBDPA_K@Z	; QPTimer::PrintCycles
$LN2@PrintMinim:
	pop	esi

; 131  : }

	pop	ebp
	ret	4
?PrintMinimumCycles@QPTimer@@QAEXPBD@Z ENDP		; QPTimer::PrintMinimumCycles
_TEXT	ENDS
; Function compile flags: /Ogtp
; File C:\Users\practicas\Downloads\spd_p9_tejado_vS2010_alumnos(1)\spd_p9_tejado_vS2010_alumnos\ej3\querypmrdtsc.cpp
_TEXT	SEGMENT
_message$ = 8						; size = 4
?PrintMinimumTime@QPTimer@@QAEXPBD@Z PROC		; QPTimer::PrintMinimumTime
; _this$ = ecx

; 122  : {

	push	ebp
	mov	ebp, esp
	push	esi
	mov	esi, ecx
	mov	ecx, OFFSET __7E111B0C_querypmrdtsc@cpp
	call	@__CheckForDebuggerJustMyCode@4
	cmp	BYTE PTR [esi+56], 0
	jne	SHORT $LN2@PrintMinim

; 123  : 	if(!DisableOutput)
; 124  : 		PrintTimeSeconds(message,&minimumTime);

	lea	eax, DWORD PTR [esi+24]
	mov	ecx, esi
	push	eax
	push	DWORD PTR _message$[ebp]
	call	?PrintTimeSeconds@QPTimer@@AAEXPBDPA_K@Z ; QPTimer::PrintTimeSeconds
$LN2@PrintMinim:
	pop	esi

; 125  : }

	pop	ebp
	ret	4
?PrintMinimumTime@QPTimer@@QAEXPBD@Z ENDP		; QPTimer::PrintMinimumTime
_TEXT	ENDS
; Function compile flags: /Ogtp
; File C:\Users\practicas\Downloads\spd_p9_tejado_vS2010_alumnos(1)\spd_p9_tejado_vS2010_alumnos\ej3\querypmrdtsc.cpp
_TEXT	SEGMENT
_MeanCycles$1 = -8					; size = 8
_message$ = 8						; size = 4
?PrintMeanCycles@QPTimer@@QAEXPBD@Z PROC		; QPTimer::PrintMeanCycles
; _this$ = ecx

; 157  : {

	push	ebp
	mov	ebp, esp
	sub	esp, 8
	push	esi
	mov	esi, ecx
	mov	ecx, OFFSET __7E111B0C_querypmrdtsc@cpp
	call	@__CheckForDebuggerJustMyCode@4
	cmp	BYTE PTR [esi+56], 0
	jne	SHORT $LN2@PrintMeanC

; 158  : 	if(!DisableOutput)
; 159  : 	{
; 160  : 		uint64_t MeanCycles ;
; 161  : 		MeanCycles = (totalTime/times);

	mov	eax, DWORD PTR [esi+40]
	cdq
	push	edx
	push	eax
	push	DWORD PTR [esi+20]
	push	DWORD PTR [esi+16]
	call	__aulldiv
	mov	DWORD PTR _MeanCycles$1[ebp], eax

; 162  : 
; 163  : 		PrintCycles(message,&MeanCycles );

	mov	ecx, esi
	lea	eax, DWORD PTR _MeanCycles$1[ebp]
	mov	DWORD PTR _MeanCycles$1[ebp+4], edx
	push	eax
	push	DWORD PTR _message$[ebp]
	call	?PrintCycles@QPTimer@@AAEXPBDPA_K@Z	; QPTimer::PrintCycles

; 164  : 		cout << "(in " << times << " measures)" <<endl;

	push	OFFSET ??$endl@DU?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@@Z ; std::endl<char,std::char_traits<char> >
	push	OFFSET $SG64224
	push	DWORD PTR [esi+40]
	push	OFFSET $SG64225
	push	DWORD PTR __imp_?cout@std@@3V?$basic_ostream@DU?$char_traits@D@std@@@1@A
	call	??$?6U?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@PBD@Z ; std::operator<<<std::char_traits<char> >
	add	esp, 8
	mov	ecx, eax
	call	DWORD PTR __imp_??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@H@Z
	push	eax
	call	??$?6U?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@PBD@Z ; std::operator<<<std::char_traits<char> >
	add	esp, 8
	mov	ecx, eax
	call	DWORD PTR __imp_??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@P6AAAV01@AAV01@@Z@Z
$LN2@PrintMeanC:
	pop	esi

; 165  : 	}
; 166  : }

	mov	esp, ebp
	pop	ebp
	ret	4
?PrintMeanCycles@QPTimer@@QAEXPBD@Z ENDP		; QPTimer::PrintMeanCycles
_TEXT	ENDS
; Function compile flags: /Ogtp
; File C:\Users\practicas\Downloads\spd_p9_tejado_vS2010_alumnos(1)\spd_p9_tejado_vS2010_alumnos\ej3\querypmrdtsc.cpp
_TEXT	SEGMENT
_MeanTime$1 = -8					; size = 8
_message$ = 8						; size = 4
?PrintMeanTime@QPTimer@@QAEXPBD@Z PROC			; QPTimer::PrintMeanTime
; _this$ = ecx

; 145  : {

	push	ebp
	mov	ebp, esp
	sub	esp, 8
	push	esi
	mov	esi, ecx
	mov	ecx, OFFSET __7E111B0C_querypmrdtsc@cpp
	call	@__CheckForDebuggerJustMyCode@4
	cmp	BYTE PTR [esi+56], 0
	jne	SHORT $LN2@PrintMeanT

; 146  : 	if(!DisableOutput)
; 147  : 	{
; 148  : 		uint64_t MeanTime ;
; 149  : 		MeanTime = (totalTime/times);

	mov	eax, DWORD PTR [esi+40]
	cdq
	push	edx
	push	eax
	push	DWORD PTR [esi+20]
	push	DWORD PTR [esi+16]
	call	__aulldiv
	mov	DWORD PTR _MeanTime$1[ebp], eax

; 150  : 
; 151  : 		PrintTimeSeconds(message,&MeanTime);

	mov	ecx, esi
	lea	eax, DWORD PTR _MeanTime$1[ebp]
	mov	DWORD PTR _MeanTime$1[ebp+4], edx
	push	eax
	push	DWORD PTR _message$[ebp]
	call	?PrintTimeSeconds@QPTimer@@AAEXPBDPA_K@Z ; QPTimer::PrintTimeSeconds

; 152  : 		cout << "   (in " << times << " measures)" <<endl;

	push	OFFSET ??$endl@DU?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@@Z ; std::endl<char,std::char_traits<char> >
	push	OFFSET $SG64210
	push	DWORD PTR [esi+40]
	push	OFFSET $SG64211
	push	DWORD PTR __imp_?cout@std@@3V?$basic_ostream@DU?$char_traits@D@std@@@1@A
	call	??$?6U?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@PBD@Z ; std::operator<<<std::char_traits<char> >
	add	esp, 8
	mov	ecx, eax
	call	DWORD PTR __imp_??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@H@Z
	push	eax
	call	??$?6U?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@PBD@Z ; std::operator<<<std::char_traits<char> >
	add	esp, 8
	mov	ecx, eax
	call	DWORD PTR __imp_??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@P6AAAV01@AAV01@@Z@Z
$LN2@PrintMeanT:
	pop	esi

; 153  : 	}
; 154  : }

	mov	esp, ebp
	pop	ebp
	ret	4
?PrintMeanTime@QPTimer@@QAEXPBD@Z ENDP			; QPTimer::PrintMeanTime
_TEXT	ENDS
; Function compile flags: /Ogtp
; File C:\Users\practicas\Downloads\spd_p9_tejado_vS2010_alumnos(1)\spd_p9_tejado_vS2010_alumnos\ej3\querypmrdtsc.cpp
_TEXT	SEGMENT
_message$ = 8						; size = 4
?PrintCycles@QPTimer@@QAEXPBD@Z PROC			; QPTimer::PrintCycles
; _this$ = ecx

; 116  : {

	push	ebp
	mov	ebp, esp
	push	esi
	mov	esi, ecx
	mov	ecx, OFFSET __7E111B0C_querypmrdtsc@cpp
	call	@__CheckForDebuggerJustMyCode@4
	cmp	BYTE PTR [esi+56], 0
	jne	SHORT $LN2@PrintCycle

; 117  : 	if(!DisableOutput)
; 118  : 		PrintCycles(message,&result);

	lea	eax, DWORD PTR [esi+8]
	mov	ecx, esi
	push	eax
	push	DWORD PTR _message$[ebp]
	call	?PrintCycles@QPTimer@@AAEXPBDPA_K@Z	; QPTimer::PrintCycles
$LN2@PrintCycle:
	pop	esi

; 119  : }

	pop	ebp
	ret	4
?PrintCycles@QPTimer@@QAEXPBD@Z ENDP			; QPTimer::PrintCycles
_TEXT	ENDS
; Function compile flags: /Ogtp
; File C:\Users\practicas\Downloads\spd_p9_tejado_vS2010_alumnos(1)\spd_p9_tejado_vS2010_alumnos\ej3\querypmrdtsc.cpp
_TEXT	SEGMENT
_message$ = 8						; size = 4
?PrintTime@QPTimer@@QAEXPBD@Z PROC			; QPTimer::PrintTime
; _this$ = ecx

; 110  : {

	push	ebp
	mov	ebp, esp
	push	esi
	mov	esi, ecx
	mov	ecx, OFFSET __7E111B0C_querypmrdtsc@cpp
	call	@__CheckForDebuggerJustMyCode@4
	cmp	BYTE PTR [esi+56], 0
	jne	SHORT $LN2@PrintTime

; 111  : 	if(!DisableOutput)
; 112  : 		PrintTimeSeconds(message,&result);

	lea	eax, DWORD PTR [esi+8]
	mov	ecx, esi
	push	eax
	push	DWORD PTR _message$[ebp]
	call	?PrintTimeSeconds@QPTimer@@AAEXPBDPA_K@Z ; QPTimer::PrintTimeSeconds
$LN2@PrintTime:
	pop	esi

; 113  : }

	pop	ebp
	ret	4
?PrintTime@QPTimer@@QAEXPBD@Z ENDP			; QPTimer::PrintTime
_TEXT	ENDS
; Function compile flags: /Ogtp
; File C:\Users\practicas\Downloads\spd_p9_tejado_vS2010_alumnos(1)\spd_p9_tejado_vS2010_alumnos\ej3\querypmrdtsc.cpp
_TEXT	SEGMENT
?ResetAll@QPTimer@@QAEXXZ PROC				; QPTimer::ResetAll
; _this$ = ecx

; 100  : {

	push	esi
	mov	esi, ecx
	mov	ecx, OFFSET __7E111B0C_querypmrdtsc@cpp
	call	@__CheckForDebuggerJustMyCode@4
	mov	DWORD PTR [esi+8], 0
	mov	DWORD PTR [esi+12], 0
	mov	DWORD PTR [esi+24], -1
	mov	DWORD PTR [esi+28], -1
	mov	DWORD PTR [esi+16], 0
	mov	DWORD PTR [esi+20], 0
	mov	DWORD PTR [esi+40], 0
	pop	esi
	ret	0
?ResetAll@QPTimer@@QAEXXZ ENDP				; QPTimer::ResetAll
_TEXT	ENDS
; Function compile flags: /Ogtp
; File C:\Users\practicas\Downloads\spd_p9_tejado_vS2010_alumnos(1)\spd_p9_tejado_vS2010_alumnos\ej3\querypmrdtsc.cpp
_TEXT	SEGMENT
?Reset@QPTimer@@QAEXXZ PROC				; QPTimer::Reset
; _this$ = ecx

; 94   : {

	push	esi
	mov	esi, ecx
	mov	ecx, OFFSET __7E111B0C_querypmrdtsc@cpp
	call	@__CheckForDebuggerJustMyCode@4
	mov	DWORD PTR [esi+8], 0
	mov	DWORD PTR [esi+12], 0
	pop	esi
	ret	0
?Reset@QPTimer@@QAEXXZ ENDP				; QPTimer::Reset
_TEXT	ENDS
; Function compile flags: /Ogtp
; File C:\Users\practicas\Downloads\spd_p9_tejado_vS2010_alumnos(1)\spd_p9_tejado_vS2010_alumnos\ej3\querypmrdtsc.cpp
_TEXT	SEGMENT
_now$1 = -16						; size = 8
_r$2 = -8						; size = 8
?Calibrate@QPTimer@@QAEXXZ PROC				; QPTimer::Calibrate
; _this$ = ecx

; 72   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 16					; 00000010H
	push	esi
	mov	esi, ecx
	mov	ecx, OFFSET __7E111B0C_querypmrdtsc@cpp
	push	edi
	call	@__CheckForDebuggerJustMyCode@4
	mov	DWORD PTR [esi+32], -1
	mov	edi, 50					; 00000032H
	mov	DWORD PTR [esi+36], -1
$LL4@Calibrate:

; 77   : 	{
; 78   : 		uint64_t r;
; 79   : 		uint64_t now;
; 80   : 
; 81   : 		ReadCycles(&startTime);

	push	esi
	mov	ecx, esi
	call	?ReadCycles@QPTimer@@AAEXPA_K@Z		; QPTimer::ReadCycles

; 82   : 		ReadCycles(&now);

	lea	eax, DWORD PTR _now$1[ebp]
	mov	ecx, esi
	push	eax
	call	?ReadCycles@QPTimer@@AAEXPA_K@Z		; QPTimer::ReadCycles

; 83   : 
; 84   : 		RestCycles(&r,&now,&startTime);

	push	esi
	lea	eax, DWORD PTR _now$1[ebp]
	mov	ecx, esi
	push	eax
	lea	eax, DWORD PTR _r$2[ebp]
	push	eax
	call	?RestCycles@QPTimer@@AAEXPA_K00@Z	; QPTimer::RestCycles

; 85   : 		
; 86   : 		if (overhead > r)

	mov	ecx, DWORD PTR _r$2[ebp+4]
	cmp	DWORD PTR [esi+36], ecx
	jb	SHORT $LN2@Calibrate
	mov	eax, DWORD PTR _r$2[ebp]
	ja	SHORT $LN11@Calibrate
	cmp	DWORD PTR [esi+32], eax
	jbe	SHORT $LN2@Calibrate
$LN11@Calibrate:

; 87   : 			overhead = r;

	mov	DWORD PTR [esi+32], eax
	mov	DWORD PTR [esi+36], ecx
$LN2@Calibrate:

; 73   : 	int test_times=50;
; 74   :     overhead= UINT64_MAX;
; 75   : 
; 76   : 	for (int i=0; i<test_times; i++)

	sub	edi, 1
	jne	SHORT $LL4@Calibrate

; 88   : 	}
; 89   : 	ResetAll();

	mov	ecx, esi
	call	?ResetAll@QPTimer@@QAEXXZ		; QPTimer::ResetAll
	pop	edi
	pop	esi

; 90   : }

	mov	esp, ebp
	pop	ebp
	ret	0
?Calibrate@QPTimer@@QAEXXZ ENDP				; QPTimer::Calibrate
_TEXT	ENDS
; Function compile flags: /Ogtp
; File C:\Users\practicas\Downloads\spd_p9_tejado_vS2010_alumnos(1)\spd_p9_tejado_vS2010_alumnos\ej3\querypmrdtsc.cpp
_TEXT	SEGMENT
_now$ = -16						; size = 8
_r$ = -8						; size = 8
?Stop@QPTimer@@QAEXXZ PROC				; QPTimer::Stop
; _this$ = ecx

; 53   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 16					; 00000010H
	push	esi
	push	edi
	mov	edi, ecx
	mov	ecx, OFFSET __7E111B0C_querypmrdtsc@cpp
	call	@__CheckForDebuggerJustMyCode@4
	lea	eax, DWORD PTR _now$[ebp]
	mov	ecx, edi
	push	eax
	call	?ReadCycles@QPTimer@@AAEXPA_K@Z		; QPTimer::ReadCycles
	push	edi
	lea	eax, DWORD PTR _now$[ebp]
	mov	ecx, edi
	push	eax
	lea	eax, DWORD PTR _r$[ebp]
	push	eax
	call	?RestCycles@QPTimer@@AAEXPA_K00@Z	; QPTimer::RestCycles
	lea	eax, DWORD PTR [edi+32]
	mov	ecx, edi
	push	eax
	lea	eax, DWORD PTR _r$[ebp]
	push	eax
	push	eax
	call	?RestCycles@QPTimer@@AAEXPA_K00@Z	; QPTimer::RestCycles
	lea	eax, DWORD PTR _r$[ebp]
	mov	ecx, edi
	push	eax
	lea	esi, DWORD PTR [edi+8]
	push	esi
	push	esi
	call	?AddCycles@QPTimer@@AAEXPA_K00@Z	; QPTimer::AddCycles
	lea	ecx, DWORD PTR _r$[ebp]
	push	ecx
	lea	eax, DWORD PTR [edi+16]
	mov	ecx, edi
	push	eax
	push	eax
	call	?AddCycles@QPTimer@@AAEXPA_K00@Z	; QPTimer::AddCycles
	mov	ecx, DWORD PTR [esi+4]
	mov	eax, DWORD PTR [esi]
	cmp	DWORD PTR [edi+28], ecx
	jb	SHORT $LN6@Stop

; 54   : 	uint64_t now;
; 55   : 	ReadCycles(&now);
; 56   : 
; 57   : 	uint64_t r;
; 58   : 	RestCycles(&r,&now,&startTime);
; 59   : 	RestCycles(&r,&r,&overhead);
; 60   : 
; 61   : 	AddCycles(&result,&result,&r);
; 62   : 
; 63   : 	AddCycles(&totalTime,&totalTime,&r);
; 64   : 
; 65   : 	if (minimumTime > result)

	ja	SHORT $LN4@Stop
	cmp	DWORD PTR [edi+24], eax
	jbe	SHORT $LN6@Stop
$LN4@Stop:

; 66   : 			minimumTime = result;

	mov	DWORD PTR [edi+24], eax
	mov	DWORD PTR [edi+28], ecx
$LN6@Stop:

; 67   : 
; 68   : 	times++;
; 69   : }

	inc	DWORD PTR [edi+40]
	pop	edi
	pop	esi
	mov	esp, ebp
	pop	ebp
	ret	0
?Stop@QPTimer@@QAEXXZ ENDP				; QPTimer::Stop
_TEXT	ENDS
; Function compile flags: /Ogtp
; File C:\Users\practicas\Downloads\spd_p9_tejado_vS2010_alumnos(1)\spd_p9_tejado_vS2010_alumnos\ej3\querypmrdtsc.cpp
_TEXT	SEGMENT
?Start@QPTimer@@QAEXXZ PROC				; QPTimer::Start
; _this$ = ecx

; 48   : {

	push	esi
	mov	esi, ecx
	mov	ecx, OFFSET __7E111B0C_querypmrdtsc@cpp
	call	@__CheckForDebuggerJustMyCode@4
	push	esi
	mov	ecx, esi
	call	?ReadCycles@QPTimer@@AAEXPA_K@Z		; QPTimer::ReadCycles
	pop	esi
	ret	0
?Start@QPTimer@@QAEXXZ ENDP				; QPTimer::Start
_TEXT	ENDS
; Function compile flags: /Ogtp
; File C:\Users\practicas\Downloads\spd_p9_tejado_vS2010_alumnos(1)\spd_p9_tejado_vS2010_alumnos\ej3\querypmrdtsc.cpp
_TEXT	SEGMENT
?NumberOfMeasures@QPTimer@@QAEHXZ PROC			; QPTimer::NumberOfMeasures
; _this$ = ecx

; 168  : {

	push	esi
	mov	esi, ecx
	mov	ecx, OFFSET __7E111B0C_querypmrdtsc@cpp
	call	@__CheckForDebuggerJustMyCode@4
	mov	eax, DWORD PTR [esi+40]
	pop	esi
	ret	0
?NumberOfMeasures@QPTimer@@QAEHXZ ENDP			; QPTimer::NumberOfMeasures
_TEXT	ENDS
; Function compile flags: /Ogtp
; File C:\Users\practicas\Downloads\spd_p9_tejado_vS2010_alumnos(1)\spd_p9_tejado_vS2010_alumnos\ej3\querypmrdtsc.cpp
_TEXT	SEGMENT
??0QPTimer@@QAE@XZ PROC					; QPTimer::QPTimer
; _this$ = ecx

; 36   : {

	push	esi
	mov	esi, ecx
	mov	ecx, OFFSET __7E111B0C_querypmrdtsc@cpp
	call	@__CheckForDebuggerJustMyCode@4
	mov	ecx, esi
	mov	DWORD PTR [esi+24], -1
	mov	DWORD PTR [esi+28], -1
	mov	DWORD PTR [esi+40], 0
	mov	DWORD PTR [esi+32], 0
	mov	DWORD PTR [esi+36], 0
	mov	DWORD PTR [esi+16], 0
	mov	DWORD PTR [esi+20], 0
	call	?Reset@QPTimer@@QAEXXZ			; QPTimer::Reset
	mov	DWORD PTR [esi+48], -1094967296		; bebc2000H
	mov	eax, esi
	mov	DWORD PTR [esi+52], 0
	mov	BYTE PTR [esi+56], 0
	pop	esi
	ret	0
??0QPTimer@@QAE@XZ ENDP					; QPTimer::QPTimer
_TEXT	ENDS
; Function compile flags: /Ogtp
; File C:\Users\practicas\Downloads\spd_p9_tejado_vS2010_alumnos(1)\spd_p9_tejado_vS2010_alumnos\ej3\querypmrdtsc.cpp
_TEXT	SEGMENT
_c_add$ = 8						; size = 4
_c_final$ = 12						; size = 4
_c_init$ = 16						; size = 4
?AddCycles@QPTimer@@AAEXPA_K00@Z PROC			; QPTimer::AddCycles
; _this$ = ecx

; 234  : {

	push	ebp
	mov	ebp, esp
	mov	ecx, OFFSET __7E111B0C_querypmrdtsc@cpp
	call	@__CheckForDebuggerJustMyCode@4
	mov	ecx, DWORD PTR _c_final$[ebp]
	mov	eax, DWORD PTR _c_init$[ebp]
	mov	edx, DWORD PTR [ecx]
	add	edx, DWORD PTR [eax]
	mov	ecx, DWORD PTR [ecx+4]
	adc	ecx, DWORD PTR [eax+4]
	mov	eax, DWORD PTR _c_add$[ebp]
	mov	DWORD PTR [eax], edx
	mov	DWORD PTR [eax+4], ecx

; 235  : 	*c_add=*c_final+*c_init;
; 236  : }

	pop	ebp
	ret	12					; 0000000cH
?AddCycles@QPTimer@@AAEXPA_K00@Z ENDP			; QPTimer::AddCycles
_TEXT	ENDS
; Function compile flags: /Ogtp
; File C:\Users\practicas\Downloads\spd_p9_tejado_vS2010_alumnos(1)\spd_p9_tejado_vS2010_alumnos\ej3\querypmrdtsc.cpp
_TEXT	SEGMENT
_c_dif$ = 8						; size = 4
_c_final$ = 12						; size = 4
_c_init$ = 16						; size = 4
?RestCycles@QPTimer@@AAEXPA_K00@Z PROC			; QPTimer::RestCycles
; _this$ = ecx

; 228  : {

	push	ebp
	mov	ebp, esp
	mov	ecx, OFFSET __7E111B0C_querypmrdtsc@cpp
	call	@__CheckForDebuggerJustMyCode@4
	mov	ecx, DWORD PTR _c_final$[ebp]
	mov	eax, DWORD PTR _c_init$[ebp]
	mov	edx, DWORD PTR [ecx]
	sub	edx, DWORD PTR [eax]
	mov	ecx, DWORD PTR [ecx+4]
	sbb	ecx, DWORD PTR [eax+4]
	mov	eax, DWORD PTR _c_dif$[ebp]
	mov	DWORD PTR [eax], edx
	mov	DWORD PTR [eax+4], ecx

; 229  : 	*c_dif=*c_final-*c_init;
; 230  : 
; 231  : }

	pop	ebp
	ret	12					; 0000000cH
?RestCycles@QPTimer@@AAEXPA_K00@Z ENDP			; QPTimer::RestCycles
_TEXT	ENDS
; Function compile flags: /Ogtp
; File C:\Users\practicas\Downloads\spd_p9_tejado_vS2010_alumnos(1)\spd_p9_tejado_vS2010_alumnos\ej3\querypmrdtsc.cpp
_TEXT	SEGMENT
tv80 = -8						; size = 8
_pc$ = 8						; size = 4
_cycles$ = 12						; size = 4
?PrintTimeSeconds@QPTimer@@AAEXPBDPA_K@Z PROC		; QPTimer::PrintTimeSeconds
; _this$ = ecx

; 222  : {   

	push	ebp
	mov	ebp, esp
	sub	esp, 8
	push	esi
	mov	esi, ecx
	mov	ecx, OFFSET __7E111B0C_querypmrdtsc@cpp
	call	@__CheckForDebuggerJustMyCode@4
	mov	ecx, DWORD PTR _cycles$[ebp]
	push	OFFSET ??$endl@DU?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@@Z ; std::endl<char,std::char_traits<char> >
	mov	edx, DWORD PTR [ecx+4]
	mov	ecx, DWORD PTR [ecx]
	call	__ultod3
	mov	edx, DWORD PTR [esi+52]
	mov	ecx, DWORD PTR [esi+48]
	movsd	QWORD PTR tv80[ebp], xmm0
	call	__ultod3
	movsd	xmm1, QWORD PTR tv80[ebp]
	sub	esp, 8
	divsd	xmm1, xmm0
	movsd	QWORD PTR [esp], xmm1
	push	DWORD PTR _pc$[ebp]
	push	DWORD PTR __imp_?cout@std@@3V?$basic_ostream@DU?$char_traits@D@std@@@1@A
	call	??$?6U?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@PBD@Z ; std::operator<<<std::char_traits<char> >
	add	esp, 8
	mov	ecx, eax
	call	DWORD PTR __imp_??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@N@Z
	mov	ecx, eax
	call	DWORD PTR __imp_??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@P6AAAV01@AAV01@@Z@Z
	pop	esi

; 223  : 	cout << pc << *cycles/(double)QPFrequencyHz << endl;
; 224  : /*	if(pc!=NULL && strlen(pc)>0)
; 225  : 		printf("%s",pc);		*/
; 226  : }

	mov	esp, ebp
	pop	ebp
	ret	8
?PrintTimeSeconds@QPTimer@@AAEXPBDPA_K@Z ENDP		; QPTimer::PrintTimeSeconds
_TEXT	ENDS
; Function compile flags: /Ogtp
; File C:\Users\practicas\Downloads\spd_p9_tejado_vS2010_alumnos(1)\spd_p9_tejado_vS2010_alumnos\ej3\querypmrdtsc.cpp
_TEXT	SEGMENT
tv73 = -8						; size = 8
_cycles$ = 8						; size = 4
_NumberOfIterations$ = 12				; size = 4
?GetCyclesByIteration@QPTimer@@AAENPA_KH@Z PROC		; QPTimer::GetCyclesByIteration
; _this$ = ecx

; 216  : {

	push	ebp
	mov	ebp, esp
	sub	esp, 8
	mov	ecx, OFFSET __7E111B0C_querypmrdtsc@cpp
	call	@__CheckForDebuggerJustMyCode@4
	mov	ecx, DWORD PTR _cycles$[ebp]
	mov	edx, DWORD PTR [ecx+4]
	mov	ecx, DWORD PTR [ecx]
	call	__ultod3
	movd	xmm1, DWORD PTR _NumberOfIterations$[ebp]
	cvtdq2pd xmm1, xmm1
	divsd	xmm0, xmm1
	movsd	QWORD PTR tv73[ebp], xmm0
	fld	QWORD PTR tv73[ebp]

; 217  : 	return (*cycles/(double)NumberOfIterations) ;
; 218  : }	

	mov	esp, ebp
	pop	ebp
	ret	8
?GetCyclesByIteration@QPTimer@@AAENPA_KH@Z ENDP		; QPTimer::GetCyclesByIteration
_TEXT	ENDS
; Function compile flags: /Ogtp
; File C:\Users\practicas\Downloads\spd_p9_tejado_vS2010_alumnos(1)\spd_p9_tejado_vS2010_alumnos\ej3\querypmrdtsc.cpp
_TEXT	SEGMENT
_pc$ = 8						; size = 4
_cycles$ = 12						; size = 4
_NumberOfIterations$ = 16				; size = 4
?PrintCyclesByIteration@QPTimer@@AAEXPBDPA_KH@Z PROC	; QPTimer::PrintCyclesByIteration
; _this$ = ecx

; 210  : {

	push	ebp
	mov	ebp, esp
	mov	ecx, OFFSET __7E111B0C_querypmrdtsc@cpp
	call	@__CheckForDebuggerJustMyCode@4
	mov	ecx, DWORD PTR _cycles$[ebp]
	mov	edx, DWORD PTR [ecx+4]
	mov	ecx, DWORD PTR [ecx]
	call	__ultod3
	movd	xmm1, DWORD PTR _NumberOfIterations$[ebp]
	sub	esp, 8
	cvtdq2pd xmm1, xmm1
	divsd	xmm0, xmm1
	movsd	QWORD PTR [esp], xmm0
	push	DWORD PTR _pc$[ebp]
	push	DWORD PTR __imp_?cout@std@@3V?$basic_ostream@DU?$char_traits@D@std@@@1@A
	call	??$?6U?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@PBD@Z ; std::operator<<<std::char_traits<char> >
	add	esp, 8
	mov	ecx, eax
	call	DWORD PTR __imp_??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@N@Z

; 211  : 	cout << pc << *cycles/(double)NumberOfIterations ; // << endl;
; 212  : }	

	pop	ebp
	ret	12					; 0000000cH
?PrintCyclesByIteration@QPTimer@@AAEXPBDPA_KH@Z ENDP	; QPTimer::PrintCyclesByIteration
_TEXT	ENDS
; Function compile flags: /Ogtp
; File C:\Users\practicas\Downloads\spd_p9_tejado_vS2010_alumnos(1)\spd_p9_tejado_vS2010_alumnos\ej3\querypmrdtsc.cpp
_TEXT	SEGMENT
_pc$ = 8						; size = 4
_cycles$ = 12						; size = 4
?PrintCycles@QPTimer@@AAEXPBDPA_K@Z PROC		; QPTimer::PrintCycles
; _this$ = ecx

; 204  : {

	push	ebp
	mov	ebp, esp
	mov	ecx, OFFSET __7E111B0C_querypmrdtsc@cpp
	call	@__CheckForDebuggerJustMyCode@4
	mov	eax, DWORD PTR _cycles$[ebp]
	push	DWORD PTR [eax+4]
	push	DWORD PTR [eax]
	push	DWORD PTR _pc$[ebp]
	push	DWORD PTR __imp_?cout@std@@3V?$basic_ostream@DU?$char_traits@D@std@@@1@A
	call	??$?6U?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@PBD@Z ; std::operator<<<std::char_traits<char> >
	add	esp, 8
	mov	ecx, eax
	call	DWORD PTR __imp_??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@_K@Z

; 205  : 	cout << pc << *cycles ;
; 206  : }	

	pop	ebp
	ret	8
?PrintCycles@QPTimer@@AAEXPBDPA_K@Z ENDP		; QPTimer::PrintCycles
_TEXT	ENDS
; Function compile flags: /Ogtp
; File C:\Users\practicas\Downloads\spd_p9_tejado_vS2010_alumnos(1)\spd_p9_tejado_vS2010_alumnos\ej3\querypmrdtsc.cpp
_TEXT	SEGMENT
_cycles$ = 8						; size = 4
?ReadCycles@QPTimer@@AAEXPA_K@Z PROC			; QPTimer::ReadCycles
; _this$ = ecx

; 196  : {

	push	ebp
	mov	ebp, esp
	mov	ecx, OFFSET __7E111B0C_querypmrdtsc@cpp
	call	@__CheckForDebuggerJustMyCode@4
	mov	ecx, DWORD PTR _cycles$[ebp]
	rdtsc
	mov	DWORD PTR [ecx], eax
	mov	DWORD PTR [ecx+4], edx

; 197  : 	uint64_t time;
; 198  : 
; 199  : 	time = __rdtsc();
; 200  :     *cycles = time;
; 201  : }

	pop	ebp
	ret	4
?ReadCycles@QPTimer@@AAEXPA_K@Z ENDP			; QPTimer::ReadCycles
_TEXT	ENDS
; Function compile flags: /Ogtp
; File C:\Users\practicas\Downloads\spd_p9_tejado_vS2010_alumnos(1)\spd_p9_tejado_vS2010_alumnos\ej3\querypmrdtsc.cpp
;	COMDAT ?__empty_global_delete@@YAXPAXI@Z
_TEXT	SEGMENT
___formal$ = 8						; size = 4
___formal$ = 12						; size = 4
?__empty_global_delete@@YAXPAXI@Z PROC			; __empty_global_delete, COMDAT
	mov	ecx, OFFSET __7E111B0C_querypmrdtsc@cpp
	jmp	@__CheckForDebuggerJustMyCode@4
?__empty_global_delete@@YAXPAXI@Z ENDP			; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Ogtp
; File C:\Users\practicas\Downloads\spd_p9_tejado_vS2010_alumnos(1)\spd_p9_tejado_vS2010_alumnos\ej3\querypmrdtsc.cpp
;	COMDAT ?__empty_global_delete@@YAXPAX@Z
_TEXT	SEGMENT
___formal$ = 8						; size = 4
?__empty_global_delete@@YAXPAX@Z PROC			; __empty_global_delete, COMDAT
	mov	ecx, OFFSET __7E111B0C_querypmrdtsc@cpp
	jmp	@__CheckForDebuggerJustMyCode@4
?__empty_global_delete@@YAXPAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
